global:
  istio:
    enabled: true
    injection: enabled

  image:
    pullPolicy: IfNotPresent

  hosts:
    domain: ###ZARF_VAR_DOMAIN###
    gitlab:
      name: gitlab.###ZARF_VAR_DOMAIN###
    registry:
      name: registry.###ZARF_VAR_DOMAIN###
    pages:
      name: pages.###ZARF_VAR_DOMAIN###
  psql:
    host: ###ZARF_VAR_GITLAB_DB_ENDPOINT###
    port: 5432
    username: ###ZARF_VAR_GITLAB_DB_USERNAME###
    database: ###ZARF_VAR_GITLAB_DB_NAME###
    password:
      useSecret: true
      secret: gitlab-postgres
      key: password

  redis:
    scheme: ###ZARF_VAR_GITLAB_REDIS_SCHEME###
    host: ###ZARF_VAR_GITLAB_REDIS_ENDPOINT###
    port: 6379
    auth:
      enabled: true
      secret: gitlab-redis
      key: password

  minio:
    enabled: false
    credentials: {}
      # secret:

  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-object-store
        key: connection
    lfs:
      bucket: uds-gitlab-lfs###ZARF_VAR_BUCKET_SUFFIX###
    artifacts:
      bucket: uds-gitlab-artifacts###ZARF_VAR_BUCKET_SUFFIX###
    uploads:
      bucket: uds-gitlab-uploads###ZARF_VAR_BUCKET_SUFFIX###
    packages:
      bucket: uds-gitlab-packages###ZARF_VAR_BUCKET_SUFFIX###
    externalDiffs:
      bucket: uds-gitlab-mr-diffs###ZARF_VAR_BUCKET_SUFFIX###
    terraformState:
      bucket: uds-gitlab-terraform-state###ZARF_VAR_BUCKET_SUFFIX###
    ciSecureFiles:
      bucket: uds-gitlab-ci-secure-files###ZARF_VAR_BUCKET_SUFFIX###
    dependencyProxy:
      bucket: uds-gitlab-dependency-proxy###ZARF_VAR_BUCKET_SUFFIX###
    backups:
      bucket: uds-gitlab-backups###ZARF_VAR_BUCKET_SUFFIX###
      tmpBucket: uds-gitlab-tmp###ZARF_VAR_BUCKET_SUFFIX###
    ## https://docs.gitlab.com/charts/charts/globals#omniauth
    omniauth:
      enabled: false
    initialDefaults: 
      signupEnabled: ###ZARF_VAR_GITLAB_SIGNUP_ENABLED###

  registry:
    bucket: uds-gitlab-registry###ZARF_VAR_BUCKET_SUFFIX###
    relativeurls: true

  pages:
    enabled: ###ZARF_VAR_GITLAB_PAGES_ENABLED###
    objectStore:
      bucket: uds-gitlab-pages###ZARF_VAR_BUCKET_SUFFIX###

postgresql:
  install: false
redis:
  install: false
registry:
  storage:
    redirect:
      disable: ###ZARF_VAR_DISABLE_REGISTRY_REDIRECT###
    secret: gitlab-object-store
    key: registry
  metrics:
    serviceMonitor: # TODO configure for Prometheus
      enabled: true

gitlab:
  toolbox:
    backups:
      config:
        secret: gitlab-object-store
        key: backups

  gitlab-exporter:
    enabled: true
    metrics: # TODO add Prometheus

  migrations:
    resources:
      limits:
        cpu: 500m
        memory: 4G

  webservice:
    ingress:
      enabled: false  # Local setting in subchart must be overridden
    metrics: # TODO add Prometheus
      enabled: true
      port: 8083
      serviceMonitor:
        enabled: true

istio:
  enabled: false
  injection: enabled
  gitlab:
    gateways:
    - istio-tenant-gateway/tenant-gateway
  registry:
    gateways:
    - istio-tenant-gateway/tenant-gateway
  pages:
    enabled: true
    port: 8090
    ingressLabels:
      app: tenant-ingressgateway
    gateways:
    - istio-tenant-gatway/tenant-gateway
    customDomains:
      enabled: false
    hosts:
    - '*.pages.###ZARF_VAR_DOMAIN###'

domain: ###ZARF_VAR_DOMAIN###
