name: Metadata

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  title_check:
    runs-on: ubuntu-latest
    name: Validate PR Title
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional@19.5.0
          npm install --save-dev @commitlint/cli@19.5.0

      - name: Lint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
